// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

public partial class MLModel
{
    /// <summary>
    /// model input class for MLModel.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(1)]
        [ColumnName(@"Monthly milk production (litters per cow)")]
        public float Monthly_milk_production__litters_per_cow_ { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLModel.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Monthly milk production (litters per cow)")]
        public float[] Monthly_milk_production__litters_per_cow_ { get; set; }

        [ColumnName(@"Monthly milk production (litters per cow)_LB")]
        public float[] Monthly_milk_production__litters_per_cow__LB { get; set; }

        [ColumnName(@"Monthly milk production (litters per cow)_UB")]
        public float[] Monthly_milk_production__litters_per_cow__UB { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath(@"MLModel.mlnet");

    public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input, horizon);
    }

    private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
        return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
    }
}

